### ISSUE TITLE
How to use model “SPixelNet-s16” in inference scripts?

### ISSUE THREAD

**Issue by sunxirui310** [MenghanXia/DisentangledColorization#1]
thank you for your awesome work!
I felt confused about superpixel modle “SPixelNet-s16” and "SPixelNet-s8".
how to use it if i want to test colorize and superpixel performance?

**Comment by MenghanXia** [comment]
To test colorization, you don't need to load the pretrained SPixelNet individually. Just follow the quick inference instructions, i.e. download one of the provided **colorization model** and run the commands.

We provide the pre-trained SPixelNet (“SPixelNet-s16” and "SPixelNet-s8") because it is required by colorization model training (check training details in the paper).  “SPixelNet-s16” and "SPixelNet-s8" denote pre-trained SPixelNet that uses superpixel size of 16x16 and 8x8 respectively.

**Comment by sunxirui310** [comment]
thanks.  I tried input size 512*512 by modifing `inference.py` 
`rgb_img = cv2.resize(rgb_img, (512,512), interpolation=cv2.INTER_LINEAR)`
it works as well on 1080Ti .

however ,`--no_resize` added in command line results in `CUDA out of memory.`
so any suggestions on how to train/infer  images  size 1920*1080?

**Comment by MenghanXia** [comment]
First, do inference on an image of 1920x1080 absolutely cause CUDA out of memory over a GPU 1080Ti.

For inference on image of large resolution (e.g., 1920x1080), you may first downscale the image into a lower resolution (e.g. 512x512) and do inference on that with "--no_resize ". Then, just resizing the resultant chromatic channels back to the original resolution and combine it with the original luminance channel to form a color image (1920x1080) in Lab space.  Conversion from Lab to RGB gives you the final results.
